### ISSUE TITLE
BYOIP : Support for splitting IP's into smaller block size (up to /30)

### ISSUE THREAD

**Issue by krysteksulek** [ovh/infrastructure-roadmap#121]
Edit : This issue is limited to splitting BYOIP blocks up to /30.
Splitting to /32 IPs will be addressed later.

Original comment :

Currently BYOIP feature is limted to /24 blocks only. It prevents customers to use it on bare metal servers, that doesn't support vRack (for example on RISE / GAME Ranges). 

BYOIP should allow to split imported IP's into smaller blocks including /32 and allow to move them between dedicated servers like separate failover IP's instead of the whole /24 blocks.

**Comment by sheepa** [comment]
Agree. This is on the top on our wishlist. Before this happens BYOIP is unfortunately useless for us.

**Comment by traqpl** [comment]
Definitely good idea

**Comment by petzor** [comment]
Same as @sheepa I was waiting for over 2 years to get BYOIP... Anyway for this moment it's useless. So please let's push it forward!

**Comment by krysteksulek** [comment]
@thieummm @agoude @Izaia64 Is there a chance to get feedback for this?

**Comment by spyrek10** [comment]
That's the one thing that stops me from migrating to OVH. Let's get it done

**Comment by thieummm** [comment]
Hi,

Yes this feature is definitely in our backlog and will be addressed soon. We will share more info in early 23.

**Comment by z9gege** [comment]
Definitely good idea

**Comment by krysteksulek** [comment]
Hello @thieummm @agoude , are you able to share ETA for this topic? 
It would help us in further planning.

**Comment by thieummm** [comment]
Updated issue : dividing imported range into smaller blocks, **up to /30**. This should be available by the end of June (in API mode).
Note : /32 slicing will be supported also... but later ;)

**Comment by z9gege** [comment]
how to use API mode to split ip  /28

**Comment by sheepa** [comment]
Any update on this?

**Comment by z9gege** [comment]
Can  split ip /28 now?

**Comment by sheepa** [comment]
Any updated ETA? Will the release be announced somewhere?

**Comment by z9gege** [comment]
I have several /27 IP segments purchased from ovh. How do I split them?
When I use the api function, the api returns
{
  "message": "This IP is not part of the Bring you own IP product."
}

Please help me follow up and resolve him thanks

**Comment by thieummm** [comment]
> I have several /27 IP segments purchased from ovh. How do I split them? When I use the api function, the api returns { "message": "This IP is not part of the Bring you own IP product." }
> 
> Please help me follow up and resolve him thanks

Hi,

this feature currently only works from IP blocks from outside OVH (BYOIP).

Best Regards,

Mathieu

**Comment by thieummm** [comment]
This feature is now available through the control panel.
