### ISSUE TITLE
New range of GAME servers range with next-gen networking

### ISSUE THREAD

**Issue by jslocinski** [ovh/infrastructure-roadmap#134]
As a game hosting company, I would like to benefit from fast and stable network on a GAME server ranges.

**Comment by mrc4tt** [comment]
What will this mean for us customers with a GAME dedicated server?

**Comment by jslocinski** [comment]
> What will this mean for us customers with a GAME dedicated server?

Lower latency and higher bandwidth networking will result in better quality of highly-loaded game servers. 
Also, bigger capacity of GAME DDoS Protection will offer better gaming stability during big network attacks.

**Comment by mrc4tt** [comment]
> Lower latency and higher bandwidth networking will result in better quality of highly-loaded game servers. Also, bigger capacity of GAME DDoS Protection will offer better gaming stability during big network attacks.

Will it means GAME dedicated servers will get higher bandwidth networking (for example 1-2Gbps or more?)

Will it also mean that there will be much more capacity for DDoS protection against GAME servers?

**Comment by jslocinski** [comment]
Yes, we're in the process of redesigning network infrastructure including GAME firewall for scalability. This will take a while, but we will update here when more precised roadmap is done.

**Comment by gegtor** [comment]
Hello

Are there any updates on this?

**Comment by MikeRuSe** [comment]
I join Gegtor's question.
Will this also mean more Game Protocols or the chance to add rate limits per source to specific ports?

**Comment by jslocinski** [comment]
@MikeRuSe things are moving, but nothing official yet.
If you have particular needs on protocol topic - let's open a separate case with more details to not to mix things here.

**Comment by MikeRuSe** [comment]
Regards to this topic, does the team have an approximate ETA (estimated time of arrival)?
This type of upgrades are pretty interesting for those that resell OVH dedicated servers, 1Gbps burst can sometimes be an issue when there are few customers uploading files and at the same time few users are connected to servers that consume high bandwidth. 
Also in regards to DDoS attacks, a higher bandwidth will help to absorb better the attacks and reduce de chances of NIC saturation.

**Comment by sygobit** [comment]
Is there details on what regions this new range will be available in?

**Comment by snk33** [comment]
> Is there details on what regions this new range will be available in?

Gravelines (FR), Beauharnois (CA), Warsaw (PL) at the end of October, other locations may be available later this year :
https://discord.com/channels/850031577277792286/1279032547640086548/1289257696759123969

Note that Game range will be based on Advanced range hardware.

**Comment by jslocinski** [comment]
Recent GAME-1/2 (EPYC-based) servers are now offered on new network architecture built for performance and quality.
