### ISSUE TITLE
Cloud Disk Array - NVMe clusters

### ISSUE THREAD

**Issue by agoude** [ovh/infrastructure-roadmap#163]
## User story

As a user I would like to order and then deploy NVMe-based cloud Disk Array clusters from webiste, manager and/or APIs so that I can leverage higher performance clusters.

## Follow, Vote and give your Feedback

You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord

Feel free to discuss with us on https://discord.gg/ovhcloud

**Comment by JacquesMrz** [comment]
https://www.ovhcloud.com/fr/storage-solutions/cloud-disk-array/
