### ISSUE TITLE
BYOIP Sydney

### ISSUE THREAD

**Issue by sheepa** [ovh/infrastructure-roadmap#165]
The BYOIP feature is missing from the Sydney datacenter.

Presumably this is being worked on but it would be nice to have a tracker for it so one can get notified when it's done.

**Comment by jslocinski** [comment]
Yes, we're working on it, should be available in about 2 months.

**Comment by jslocinski** [comment]
duplicate of https://github.com/ovh/infrastructure-roadmap/issues/168
