### ISSUE TITLE
GAME firewall upgrade | FiveM

### ISSUE THREAD

**Issue by MikeRuSe** [ovh/infrastructure-roadmap#174]
Opening individual issue for adding L7 FiveM option to game firewall as mentioned at: https://github.com/ovh/infrastructure-roadmap/issues/135
FiveM is now officially owned by Rockstar.
https://www.rockstargames.com/newswire/article/8971o8789584a4/roleplay-community-update
@jslocinski

**Comment by Heavens-c** [comment]
I hope this gets priority since it will transform the game for the fiveM community. Some smaller communities may also afford it because of the game firewall since Rockstar acquired the fiveM.

**Comment by jslocinski** [comment]
we're investigating..

**Comment by Manason** [comment]
@jslocinski Any update on this?

**Comment by alberttheprince** [comment]
> [@jslocinski](https://github.com/jslocinski) Any update on this?

Yeah would good to get an update on this, because atm there doesn't seem to be any sort of protection for users using OVH with FiveM, a year into it being officially owned by Rockstar.

**Comment by jslocinski** [comment]
Happy to share that FiveM is now part of GAME DDoS Protection offered with new GAME-1/2 servers!

**Comment by alberttheprince** [comment]
> Happy to share that FiveM is now part of GAME DDoS Protection offered with new GAME-1/2 servers (EPYC-based)!

So this isn't available for any other game servers/older game-1 ryzen servers?

**Comment by McLovinIt101** [comment]
> Happy to share that FiveM is now part of GAME DDoS Protection offered with new GAME-1/2 servers (EPYC-based)!

It seems quite unusual that new game DDoS protection filters aren't offered on the older servers, especially when someone is paying for a game server. Are there any plans to release the new filters for older hardware as well?

**Comment by FingerlessGlov3s** [comment]
> Happy to share that FiveM is now part of GAME DDoS Protection offered with new GAME-1/2 servers (EPYC-based)!

Is TCP as well as UDP protected?

**Comment by jslocinski** [comment]
> > Happy to share that FiveM is now part of GAME DDoS Protection offered with new GAME-1/2 servers (EPYC-based)!
> 
> Is TCP as well as UDP protected?

yes, it is.

**Comment by FingerlessGlov3s** [comment]
I'm getting 1-15% packetloss for players, varies a lot but most players get packetloss, no matter how many players.

I want to know if I toggle off and on the GAME Firewall, will it kill all FiveM connections, and cause players to disconnect? I'm wondering if the loss is caused by packets being caught by the protections or not.  Didn't have that much packetloss problems, on our old hosting providered but moved to OVH to gain the much better DDOS protection/filtering.
