### ISSUE TITLE
[Game] Minecraft Pocket Edition Incompatible With Servers Using RakNet Cookies

### ISSUE THREAD

**Issue by Kas-tle** [ovh/infrastructure-roadmap#186]
We recently pushed an update on a Minecraft Bedrock project I work on that uses a little known mechanism in the original RakNet protocol to send a proper cookie to the client in the first response packet in order to prevent UDP source IP spoofing. See https://github.com/GeyserMC/Geyser/pull/4554 which contains details and packet captures from before and after.

I believe that the OVH game firewall may already implement some sort of its own check (something along the lines of setting the MTU to a random value and checking if the client agrees to it). However, because it is not considering the cookie, I believe that our software rejects the connection as it expects to receive the valid cookie it sent the client.

Since the vanilla Minecraft Bedrock client correctly handles this, would there be any way to implement support for this on OVH so that the game firewall forwards the correct cookie to the backend server if it requests it?

**Comment by jslocinski** [comment]
Thanks @Kas-tle for the info. Will check it with the team.

**Comment by jslocinski** [comment]
Hello, the new implementation of RakNet is on the roadmap and will target next generation of GAME DDoS protection. That will be available with upcomming GAME servers (late summer).

**Comment by dries-c** [comment]
Is there a reason it won't be added to current GAME servers in the future?

**Comment by jslocinski** [comment]
> Is there a reason it won't be added to current GAME servers in the future?

Due to the complexity of this task for previous generations, we prioritized new one. New platform will secure more frequent security upgrades for future as well as new features.

**Comment by jslocinski** [comment]
Happy to share that updated Minecraft Bedrock is now offered within recent GAME-1/2 servers (EPYC-based)
