### ISSUE TITLE
NAS-HA - new ranges up to 144TB 

### ISSUE THREAD

**Issue by Izaia64** [ovh/infrastructure-roadmap#63]
As a customer, i need volume of file storage with large capacity 
I need for my usage SSD performances
Usage : radiology, videos

**Comment by agoude** [comment]
We are happy to let you know that we just launched the refresh of NAS-HA, here are below some of the key highlights:

-	New tiers of storage from 3TB up to 144TB per service for large capacity needs (SSD RAID 10)
-	A brand new userexperience in the control panel
-	Commitment options
-	Availability in RBX, SBG and BHS 

More information here: https://www.ovhcloud.com/en-gb/storage-solutions/nas-ha/
