### ISSUE TITLE
NAS-HA - NFSv4.1

### ISSUE THREAD

**Issue by Izaia64** [ovh/infrastructure-roadmap#64]
As a customer i want to consume my storage volume through a standard protocole NFS version 4

**Comment by agoude** [comment]
Update: change will happen starting October 10th on existing NAS-HA servers. Starting this date, NFSv4.1 will be supported on all SSD-based NAS-HA

**Comment by agoude** [comment]
Change is now complete on all SSD-based NAS-HA. Support for NFSv4.1 is available.
