### ISSUE TITLE
Additional IP (IP failover) user experience update

### ISSUE THREAD

**Issue by thieummm** [ovh/infrastructure-roadmap#73]
- Better control panel :

Basic/Advanced mode
Better look and feel
Better responsivity
Dedicated tab for Additional IP
Better contextual help
Quick access to a service associated with an IP
Better alert performance (better loading time)

- Better order experience
- Bugfixes

**Comment by GillesFr06** [comment]
Bonjour,
Plus d'infos possibles ?
Quels changements ?
Est-ce déjà en place ?
Merci, Gilles

**Comment by thieummm** [comment]
Hello,

thanks for your interest !

For now I can only share that user experience will be improved :)
Not in prod right now, should be ready by the end of the year.

**Comment by olivier-lz** [comment]
Hi,
this subject include IPv6 failover without IPv4 ?
Thanks.

**Comment by Seb-Renaud** [comment]
Delivered & closed
