### ISSUE TITLE
Anti-DDoS Infrastructure: manager security dashboard

### ISSUE THREAD

**Issue by thieummm** [ovh/infrastructure-roadmap#78]
As a user, I want to get more information about actual attacks on my infrastructure so that I can better understand how they are mitigated by the Anti-DDoS Infrastructure solution

**Comment by jslocinski** [comment]
https://labs.ovhcloud.com/en/network-security-dashboard/

**Comment by jslocinski** [comment]
Security Dashboard was pushed on production worldwide together with recent updates following Beta feedbacks.

**Comment by Entrana-RSPS** [comment]
does not display a whole lot of info, it is very difficult for an average server owner to understand whats going on
